# docker-compose.yml
version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DEBUG=0
      - AI_PROVIDER=gemini
      - GEMINI_API_KEY=GEMINI_API_KEY
      - SECRET_KEY=&8i3v^=))u1o2vao+brm3uk8#&x(f=qm!!e6y95(-_71q+sg!_
      - DATABASE_URL=postgresql://postgres:YQdIzMbIRCLrVVVqmjeGArkmLotdXDQm@postgres.railway.internal:5432/railway
      - ALLOWED_HOSTS=curhatin2-production.up.railway.app
    volumes:
      - ./logs:/app/logs
     command: >
  sh -c "python manage.py migrate --noinput &&
         python manage.py collectstatic --noinput &&
         gunicorn mental_health_chatbot.wsgi:application --bind 0.0.0.0:${PORT} --workers 3 --log-level info"

